name: Build and Run Tests by Bazel
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - develop
jobs:
  build:
    name: BuildBazel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bazel build
      - name: Run Tests
        run: bazel test
